### PR TITLE
Restore previous custom color of previous hovered tree item

### PR DESCRIPTION
**Pull request by AeioMuch**
Fix https://github.com/godotengine/godot/pull/99700#issuecomment-2530665886

But maybe you have a better solution in mind ?

### CODE REVIEW

**Comment by AeioMuch** [comment]
> I have changed this code after realizing that the custom_color meta doesn't need to be changed on hover at all. Now I just use it to restore the old color.

There's a bug with the way you are doing it right now :

https://github.com/user-attachments/assets/1900a021-2a18-404c-a4fa-55ffbb5c6d29

**Comment by hpvb** [comment]
What are you doing there exactly? I don't think I follow

**Comment by AeioMuch** [comment]
> What are you doing there exactly? I don't think I follow

I just take one node and hover another, then once it's highlighted, I hover another one until it's highlighted again, etc. The previous one will become transparent.

**Comment by hpvb** [comment]
I guess clear_custom_color doesn't quite do what I expect then, that is strange as that is what the old code did. I'll look at it again.

**Comment by hpvb** [comment]
Fixed! Was just a really silly typo. I was comparing against Color(0,0,0) instead of Color(0,0,0,0)

**Comment by AeioMuch** [comment]
Awesome! Make sense :) A lot cleaner also! Thank you 👍

**Comment by hpvb** [comment]
Thanks! <3

**Pull request closed without merging**
